# Generated by Django 2.2.5 on 2019-10-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_hidden',
        ),
        migrations.AddField(
            model_name='post',
            name='allow_reply',
            field=models.BooleanField(default=False, verbose_name='댓글 허용'),
        ),
        migrations.AddField(
            model_name='post',
            name='scope',
            field=models.CharField(choices=[('HIDDEN', '비공개'), ('STAFF', '스탭 공개'), ('PUBLIC', '전체 공개')], default=True, max_length=40, verbose_name='공개 범위'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성된 날짜'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='게시글 이름'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정된 날짜'),
        ),
    ]
