# Generated by Django 2.2.5 on 2019-10-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191022_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('link', models.URLField()),
                ('index', models.IntegerField(db_index=0)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=1)),
                ('super_menu', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Menu')),
            ],
        ),
    ]
