# Generated by Django 2.2.5 on 2019-10-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
