# Generated by Django 2.2.5 on 2019-10-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191025_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
