# Generated by Django 2.2.5 on 2019-10-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191025_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='link',
        ),
    ]
